### ISSUE TITLE
Encounter memory error when running graph_creation3.py on Windows 11

### ISSUE THREAD

**Issue by jiqicn** [davideceolin/FAReviews#11]
See error message below:

```shell
(knime) PS C:\Workspace\python_projects\FAReviews> python .\graph_creation3.py
Please provide the file path (csv) for the input data (reviews): C:\Workspace\python_projects\FAReviews\test_case\AMAZON_FASHION_5_reviews.csv
Please provide the file path (pkl) for the input data (product list): C:\Workspace\python_projects\FAReviews\test_case\AMAZON_FASHION_5_prods.pkl  
Your logical CPU count is: 8
Define number of usable cpu (optional, default is 8):
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\qiji1\anaconda3\envs\knime\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\qiji1\anaconda3\envs\knime\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Workspace\python_projects\FAReviews\graph_creation3.py", line 70, in add_features
    df['matrix', 'clusters'] = df['prod'].apply(lambda x: get_matrix_and_clusters(x,
  File "C:\Users\qiji1\anaconda3\envs\knime\lib\site-packages\pandas\core\series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "C:\Users\qiji1\anaconda3\envs\knime\lib\site-packages\pandas\core\apply.py", line 1082, in apply
    return self.apply_standard()
  File "C:\Users\qiji1\anaconda3\envs\knime\lib\site-packages\pandas\core\apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas\_libs\lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "C:\Workspace\python_projects\FAReviews\graph_creation3.py", line 70, in <lambda>
    df['matrix', 'clusters'] = df['prod'].apply(lambda x: get_matrix_and_clusters(x,
  File "C:\Workspace\python_projects\FAReviews\graph_creation3.py", line 36, in get_matrix_and_clusters
    dists = list(itertools.starmap(model.wmdistance, combis))
  File "C:\Users\qiji1\anaconda3\envs\knime\lib\site-packages\gensim\models\keyedvectors.py", line 984, in wmdistance     
    v1 = np.array([self.get_vector(token, norm=norm) for token in doclist1])
  File "C:\Users\qiji1\anaconda3\envs\knime\lib\site-packages\gensim\models\keyedvectors.py", line 984, in <listcomp>     
    v1 = np.array([self.get_vector(token, norm=norm) for token in doclist1])
  File "C:\Users\qiji1\anaconda3\envs\knime\lib\site-packages\gensim\models\keyedvectors.py", line 449, in get_vector     
    self.fill_norms()
  File "C:\Users\qiji1\anaconda3\envs\knime\lib\site-packages\gensim\models\keyedvectors.py", line 709, in fill_norms     
    self.norms = np.linalg.norm(self.vectors, axis=1)
  File "<__array_function__ internals>", line 180, in norm
  File "C:\Users\qiji1\anaconda3\envs\knime\lib\site-packages\numpy\linalg\linalg.py", line 2556, in norm
    s = (x.conj() * x).real
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 3.35 GiB for an array with shape (3000000, 300) and data type float32
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Workspace\python_projects\FAReviews\graph_creation3.py", line 98, in <module>
    df_prods_mc = run_graph_creation(df_reviews, df_prods, nc)
  File "C:\Workspace\python_projects\FAReviews\graph_creation3.py", line 87, in run_graph_creation
    df_prods_mc = parallelize_dataframe(df_prods, func=add_features_df, n_cores=nc)
  File "C:\Workspace\python_projects\FAReviews\graph_creation3.py", line 79, in parallelize_dataframe
    df_res = pd.concat(pool.starmap(func, zip(df_split, range(n_cores))))
  File "C:\Users\qiji1\anaconda3\envs\knime\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\qiji1\anaconda3\envs\knime\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 3.35 GiB for an array with shape (3000000, 300) and data type float32
```
And here is the device specifications:

```
Processor	11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz   3.00 GHz
Installed RAM	16.0 GB (15.7 GB usable)
Device ID	3FA73998-0164-407B-B86D-2F77685DAB93
Product ID	00355-62737-58265-AAOEM
System type	64-bit operating system, x64-based processor
```

It seems that the Windows system won't overcommit memory as Linux/MacOS does.

**Comment by laurasootes** [comment]
Hi @jiqicn 
Do you have a suggestion on how to solve this issue? So far the code has only been tested on Linux and MacOS, and I can indeed find that Windows does not overcommit memory. Does it help if you try to use fewer cores?
